site_name: 'Documentación FE'

theme:
  name: null
  custom_dir: mkdocs_windmill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

# This should be renamed to nav for mkdocs 1.0+
pages:
- Home: index.md
- About: about.md

markdown_extensions:
  - toc:
      permalink: '#'

